part one on release 8.3
reason-association/rescript-lang.org pull request #61
Opened 2020-09-23 04:35 UTC by bobzhang

2020-09-23 09:28 UTC, bobzhang commented
Have no idea what's going on, need some help debugging next.js..

2020-09-23 10:21 UTC, fhammerschmidt requested changes

2020-09-23 10:21 UTC, fhammerschmidt commented on _blogposts/2020-09-23-release-8-3.mdx
> +To have better integration with other [JS infrastructures](https://github.com/rescript-lang/rescript-compiler/issues/4624), for example, Next.js/React Native, we allow file names like `404.res`, `But
Small typo: `Button.Android.res`

2020-09-23 13:46 UTC, yawaramin approved these changes

2020-09-23 17:14 UTC, jdeisenberg commented on _blogposts/2020-09-23-release-8-3.md.raw
> +In this release, we make it optional to have `bs.` prefix it or not, this will make the FFI less verbose,
In this release, we make the `bs.` prefix optional. This will make the FFI less verbose.

2020-09-23 17:14 UTC, jdeisenberg commented on _blogposts/2020-09-23-release-8-3.md.raw
> +Could be simplified as
It can now be simplified as:

2020-09-23 17:15 UTC, jdeisenberg commented on _blogposts/2020-09-23-release-8-3.md.raw
> +
Note that almost all previous attributes with `bs.xx` can be simplified as `xx` with the exception of the following two that don't have abbreviations:

2020-09-23 17:16 UTC, jdeisenberg commented on _blogposts/2020-09-23-release-8-3.md.raw
> +
In lines 46 and 48, use a semicolon instead of a comma to be grammatically correct.

2020-09-23 17:20 UTC, jdeisenberg commented on _blogposts/2020-09-23-release-8-3.md.raw
> +Previously for such piece of code:
Previously, for code like this:

2020-09-23 17:21 UTC, jdeisenberg commented on _blogposts/2020-09-23-release-8-3.md.raw
> +in this release, we make such style work out of the box without the work around like adding a module prefix like `let {N.x} = ..`
...properly. In this release, we make the original code style work out of the box without a work-around such as adding a module prefix like `let {N.x} = ..`

2020-09-24 15:39 UTC, ryyppy commented
> @ryyppy does the current blogging support displaying two syntaxes?

Discussed this feature offline (yes it is possible)


> Does the current engine supports `md` syntax as well? I wonder if I don't need jsx in md, could the engine do some work like renameing `md` into `mdx` automatically, I still use `md` syntax mostly because it has better tooling by default (preview mode without installing an extension)

I will create an issue to allow `md` files as well... but right now you are using JSX because of the multi syntax feature.

2020-09-25 00:18 UTC, bobzhang commented
@ryyppy do you have any ideal why the test fails?

2020-09-25 07:51 UTC, merged

2020-09-25 10:21 UTC, jfrolich commented
I was wondering why you would use both `bs.val` and `bs.module` at the same time in the example?